#!/usr/bin/env bash
dry_run="0"

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config hom"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z "$UTIL_PATH" ]; then
    echo "env var DEV_ENV needs to be present"
    exit 1
fi

if [[ $1 == "--dry" ]]; then
    dry_run="1"
fi

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "env: $UTIL_PATH"

update_files() {
    log "copying over files from: $1"
    pushd $1 &> /dev/null
    (
        configs=`find . -mindepth 1 -maxdepth 1 -type d`
        for c in $configs; do
            directory=${2%/}/${c#./}
            log "    creating link env: cp $c $2"
            if [[ $dry_run == "0" ]]; then
                ln -fs ./$c $2
            fi
        done

    )
    popd &> /dev/null
}

copy() {
    log "linking: $1 to $2"
    if [[ $dry_run == "0" ]]; then
        ln -fs $1 $2
    fi
}

copy $UTIL_PATH/dotfiles/nvim $HOME/.config/nvim
copy $UTIL_PATH/dotfiles/.vimrc $HOME/.vimrc

# update_files $UTIL_PATH/env/.config $XDG_CONFIG_HOME
# update_files $UTIL_PATH/env/.local $HOME/.local
#
# copy $UTIL_PATH/tmux-sessionizer/tmux-sessionizer $HOME/.local/scripts/tmux-sessionizer
# copy $UTIL_PATH/env/.zsh_profile $HOME/.zsh_profile
# copy $UTIL_PATH/env/.zshrc $HOME/.zshrc
# copy $UTIL_PATH/env/.xprofile $HOME/.xprofile
# copy $UTIL_PATH/env/.tmux-sessionizer $HOME/.tmux-sessionizer
# copy $UTIL_PATH/dev-env $HOME/.local/scripts/dev-env
