#!/usr/bin/env bash

ZOXIDE="/usr/bin/zoxide"
switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t 0:$1
    else
        tmux select-window -t $1
    fi
}

has_session() {
    tmux list-windows | grep -q -E "^[0-9]+: $1"

}

hydrate() {
    if [ -f $2/.tmux-sessionizer ]; then
        tmux send-keys -t $1 "source $2/.tmux-sessionizer" c-M
    elif [ -f $HOME/.tmux-sessionizer ]; then
        tmux send-keys -t $1 "source $HOME/.tmux-sessionizer" c-M
    fi
}

if [[ $# -eq 1 ]]; then
    query=$(\command $ZOXIDE query $1)
    if [ $? -eq 1 ]; then
        echo "zoxide query did not find anything"
        exit 1
    fi
    selected=$query
else
    selected=$(\command $ZOXIDE query --interactive)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -d
    tmux new-window -n $selected_name -c $selected
    hydrate $selected_name $selected
elif ! has_session $selected_name; then
    tmux new-window -n $selected_name -c $selected
    hydrate $selected_name $selected
fi

switch_to $selected_name

